### ISSUE TITLE
Mcmmo fishing messing with vanilla treasure/junk drops, making junk drops from mcmmo fishing count as treasures in the achievement plugin

### ISSUE THREAD

**Issue by tyrantium** [theseedmc/issues#21] opened 2019-06-20 23:37 UTC
DO NOT REPORT ONE-OFF OCCOURANCES OR PROBLEMS WITH OTHER PLAYERS HERE. REPORT BUGS AND ISSUES THARE ARE OCCOURING IN THE SERVERS CODEBASE.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Describe the bug**
The junk from mcmmo fishing messes with the achievements, making it count as treasures from the achievement plugin (also maybe stop mcmmo fishing to stop messing with vanilla fishing drops)

**To Reproduce**
1. Go to sea
2. fish
3. level up a bit on mcmmo (lvl 8-9)
4. See bug occouring

**Expected behavior**
counts as achievement when u get junk

**Comment by gp-Airee** [comment] 2019-06-21 21:30
Duplicate of #19

**Closed by gp-Airee** 2019-06-21 21:30 UTC
Labels: wontfix
