### ISSUE TITLE
crate keys "premium perks"

### ISSUE THREAD

**Issue by Fengsuave** [theseedmc/issues#64] opened 2019-07-14 20:36 UTC
![Screenshot_11](https://user-images.githubusercontent.com/52584503/61189049-1fef9b80-a64d-11e9-95b0-f5f9e26bc045.png)

It is more than 1 week that claim a key, claim it on July 4. It's already 10 days and I still can not claim the next one.

**Comment by nkomarn** [comment] 2019-07-15 04:40
@Fengsuave The timer system is broken currently for all timers that exist in the donor perks menu (including skulls, keys, and boosts). This is caused by an issue with the database code, which I will be improving. Once the database stuff is resolved, the timers will function as intended.

**Comment by Fengsuave** [comment] 2019-07-15 15:36
thanks for the reply. then I'll wait for him to fix it <3

**Comment by nkomarn** [comment] 2019-07-16 05:24
Resolved in build 7 of SeedDonor.

**Closed by nkomarn** 2019-07-16 05:24 UTC
Labels: bug
