### ISSUE TITLE
Voting doesn't work on melon

### ISSUE THREAD

**Issue by wouter222** [theseedmc/issues#17] opened 2019-06-20 11:36 UTC
Hey ! This has happened to me and a couple of other players,

When you vote on all six sites, you won't get any rewards from it. I've seen this happening on Mushroom as well? Could someone please take a look at this, thank you!

Wouter222

**Comment by gp-Airee** [comment] 2019-06-20 18:11
Duplicate of #13

**Closed by gp-Airee** 2019-06-20 18:11 UTC
Labels: duplicate
