### ISSUE TITLE
Big slimes not splitting

### ISSUE THREAD

**Issue by Waefles** [theseedmc/issues#94] opened 2019-09-01 15:45 UTC
Currently big slimes and medium sized slimes are not splitting therefore not dropping slimeballs rendering them practically useless. The spawn rates are super low for the baby slimes making it increasingly difficult to produce an efficient slime farm. Is there anything that can be done to fix this by allowing larger slimes to split or even preventing the big and medium slimes from spawning so that farming them from a slime spawner is actually worthwhile otherwise I believe its pointless for them to be in loot crates.

Thanks 
- Waefels

**Comment by gp-Airee** [comment] 2019-09-02 06:24
In progress by developer.

**Comment by gp-Airee** [comment] 2019-09-02 06:27
Oops, duplicate of #93

**Closed by gp-Airee** 2019-09-02 06:27 UTC
Labels: bug
