### ISSUE TITLE
creating new portals

### ISSUE THREAD

**Issue by rnovamd** [theseedmc/issues#87] opened 2019-08-15 21:53 UTC
when you go through a nether portal in the overworld and come back it spawns you in the wrong place and keeps on creating new portals when you go through and come back

**Comment by rnovamd** [comment] 2019-08-15 21:54
![image](https://user-images.githubusercontent.com/54157176/63129502-8f8bda00-bfaf-11e9-955b-f8fb12b6fa02.png)

**Comment by gp-Airee** [comment] 2019-08-15 23:49
Duplicate of #75

**Closed by gp-Airee** 2019-08-15 23:49 UTC
