### ISSUE TITLE
Bug with 'mason' job - unable to get money from smelting anymore

### ISSUE THREAD

**Issue by adrenalinetooth** [theseedmc/issues#48] opened 2019-07-03 02:17 UTC
**Describe the bug**
 On Mushroom server, mason job - Smelting ANYTHING no longer gives job experience or money.

**To Reproduce**
1. Try to smelt cobble, etc
2. You will smelt the material but not receive job exp or money.

**Expected behavior**
 I would expect to get money and exp from smelting.

**Comment by nkomarn** [comment] 2019-07-04 08:24
I've heard people complain about multiple jobs being broken - not sure if they actually are, but just throwing that out there.

**Comment by nkomarn** [comment] 2019-07-04 08:24
Duplicate of #47

**Closed** 2019-07-05 00:56 UTC
